### ISSUE TITLE
Polyfill Object.assign() with es6-shim

### ISSUE THREAD

**Issue by alexbasalyga** [ericelliott/isomorphic-express-boilerplate#15]
The [browser support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility) for [Object.assign](https://github.com/ericelliott/isomorphic-express-boilerplate/blob/master/app/node_modules/lib/app.js#L20) is very poor right now.

We can polyfill it using [object-assign](https://www.npmjs.com/package/object-assign).

**Comment by ericelliott** [comment]
Or we could just use es5-shim + es6-shim, instead?

**Comment by alexbasalyga** [comment]
I don't have any experience with es6-shim. Is the overhead low?

**Comment by ericelliott** [comment]
I'm not sure. We should look into it though, as long as we're throwing the idea of polyfills around. =)

**Comment by alexbasalyga** [comment]
[Minified es6-shim](https://github.com/paulmillr/es6-shim/blob/master/es6-shim.min.js) is 34.833 kb. :0

**Comment by ericelliott** [comment]
We could forget the shim and just do the whole project in ES6 and transpile... thoughts?

**Comment by erixtekila** [comment]
https://cdn.polyfill.io/v1/docs/ made my day ;)

**Comment by ericelliott** [comment]
This project is going to use ES6 with Babel and [core-js](https://github.com/zloirock/core-js).
